module.exports = [
  {
    "city": "Austin",
    "state": "TX",
    "zipcode": 78712,
    "university": "University of Texas: Austin",
    "demandscore": 30,
    "supplyscore": 52,
    "totalscore": 82,
    "totalrank": 1,
    "totalug": 39057,
    "ugscore": 5,
    "offcampus": 0.818,
    "offcampusscore": 7,
    "parkingcost": 669,
    "pcrank": 18,
    "demandrank": 1,
    "church": 5,
    "churchscore": 40,
    "neighborhood": 0.03,
    "neighborhoodscore": 1,
    "medianincome": 19722,
    "medianincomerank": 11,
    "supplyrank": 8
  },
  {
    "city": "Berkeley",
    "state": "CA",
    "zipcode": 94720,
    "university": "University of California: Berkely",
    "demandscore": 63,
    "supplyscore": 75,
    "totalscore": 138,
    "totalrank": 2,
    "totalug": 27496,
    "ugscore": 24,
    "offcampus": 0.74,
    "offcampusscore": 36,
    "parkingcost": 1404,
    "pcrank": 3,
    "demandrank": 7,
    "church": 12,
    "churchscore": 3,
    "neighborhood": 0.2,
    "neighborhoodscore": 23,
    "medianincome": 25452,
    "medianincomerank": 49,
    "supplyrank": 10
  },
  {
    "city": "Tempe",
    "state": "AZ",
    "zipcode": 85281,
    "university": "Arizona State University",
    "demandscore": 31,
    "supplyscore": 117,
    "totalscore": 148,
    "totalrank": 3,
    "totalug": 54000,
    "ugscore": 2,
    "offcampus": 0.792,
    "offcampusscore": 15,
    "parkingcost": 780,
    "pcrank": 14,
    "demandrank": 2,
    "church": 9,
    "churchscore": 12,
    "neighborhood": 0.1,
    "neighborhoodscore": 10,
    "medianincome": 52588,
    "medianincomerank": 95,
    "supplyrank": 91
  },
  {
    "city": "Fort Collins",
    "state": "CO",
    "zipcode": 80523,
    "university": "Colorado State University: Fort Collins",
    "demandscore": 92,
    "supplyscore": 57,
    "totalscore": 149,
    "totalrank": 4,
    "totalug": 22727,
    "ugscore": 34,
    "offcampus": 0.74,
    "offcampusscore": 37,
    "parkingcost": 628,
    "pcrank": 21,
    "demandrank": 15,
    "church": 6,
    "churchscore": 24,
    "neighborhood": 0.1,
    "neighborhoodscore": 12,
    "medianincome": 21032,
    "medianincomerank": 21,
    "supplyrank": 39
  },
  {
    "city": "Ann Arbor",
    "state": "MI",
    "zipcode": 48109,
    "university": "University of Michigan: Ann Arbor",
    "demandscore": 75,
    "supplyscore": 75,
    "totalscore": 150,
    "totalrank": 5,
    "totalug": 28120,
    "ugscore": 23,
    "offcampus": 0.68,
    "offcampusscore": 50,
    "parkingcost": 1975,
    "pcrank": 2,
    "demandrank": 11,
    "church": 8,
    "churchscore": 16,
    "neighborhood": 0.1,
    "neighborhoodscore": 11,
    "medianincome": 25339,
    "medianincomerank": 48,
    "supplyrank": 5
  },
  {
    "city": "Minneapolis",
    "state": "MN",
    "zipcode": 55455,
    "university": "University of Minnesota: Twin Cities",
    "demandscore": 40,
    "supplyscore": 116,
    "totalscore": 156,
    "totalrank": 6,
    "totalug": 30511,
    "ugscore": 15,
    "offcampus": 0.774,
    "offcampusscore": 20,
    "parkingcost": 1185,
    "pcrank": 5,
    "demandrank": 4,
    "church": 2,
    "churchscore": 68,
    "neighborhood": 0.06,
    "neighborhoodscore": 4,
    "medianincome": 24784,
    "medianincomerank": 44,
    "supplyrank": 63
  },
  {
    "city": "Tucson",
    "state": "AZ",
    "zipcode": 85721,
    "university": "University of Arizona",
    "demandscore": 37,
    "supplyscore": 120,
    "totalscore": 157,
    "totalrank": 7,
    "totalug": 32964,
    "ugscore": 8,
    "offcampus": 0.8,
    "offcampusscore": 13,
    "parkingcost": 692,
    "pcrank": 16,
    "demandrank": 3,
    "church": 9,
    "churchscore": 11,
    "neighborhood": 0.3,
    "neighborhoodscore": 47,
    "medianincome": 26726,
    "medianincomerank": 62,
    "supplyrank": 92
  },
  {
    "city": "Salt Lake City",
    "state": "UT",
    "zipcode": 84112,
    "university": "University of Utah",
    "demandscore": 63,
    "supplyscore": 100,
    "totalscore": 163,
    "totalrank": 8,
    "totalug": 22761,
    "ugscore": 33,
    "offcampus": 0.85,
    "offcampusscore": 6,
    "parkingcost": 600,
    "pcrank": 24,
    "demandrank": 8,
    "church": 6,
    "churchscore": 30,
    "neighborhood": 0.1,
    "neighborhoodscore": 15,
    "medianincome": 57099,
    "medianincomerank": 55,
    "supplyrank": 78
  },
  {
    "city": "College Station",
    "state": "TX",
    "zipcode": 77843,
    "university": "Texas A&M University",
    "demandscore": 58,
    "supplyscore": 112,
    "totalscore": 170,
    "totalrank": 9,
    "totalug": 68825,
    "ugscore": 1,
    "offcampus": 0.76,
    "offcampusscore": 26,
    "parkingcost": 500,
    "pcrank": 31,
    "demandrank": 5,
    "church": 11,
    "churchscore": 8,
    "neighborhood": 1,
    "neighborhoodscore": 94,
    "medianincome": 19631,
    "medianincomerank": 10,
    "supplyrank": 26
  },
  {
    "city": "Lubbock",
    "state": "TX",
    "zipcode": 79409,
    "university": "Texas Tech University: Lubbock",
    "demandscore": 103,
    "supplyscore": 67,
    "totalscore": 170,
    "totalrank": 10,
    "totalug": 28868,
    "ugscore": 21,
    "offcampus": 0.76,
    "offcampusscore": 25,
    "parkingcost": 300,
    "pcrank": 57,
    "demandrank": 19,
    "church": 10,
    "churchscore": 10,
    "neighborhood": 0.2,
    "neighborhoodscore": 25,
    "medianincome": 22201,
    "medianincomerank": 32,
    "supplyrank": 59
  }
]
